# Server
server.port=8080

# H2 Database (????)
#spring.datasource.url=jdbc:h2:mem:semsedb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# MySQL Database
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

admin.pc.base-url=${ADMIN_PC_BASE_URL}
admin.pc.username=${ADMIN_PC_USERNAME}
admin.pc.password=${ADMIN_PC_PASSWORD}

# H2 Console (????)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# data.sql ?? ??
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# LocalDateTime ? "2026-05-23T14:30:00" ??? ??? (?? ??)
spring.jackson.serialization.write-dates-as-timestamps=false