server.port=5000

# DB - MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/semsedb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# AdminPC-Server ??
admin.pc.base-url=http://localhost:5000
admin.pc.username=admin
admin.pc.password=admin1234

# ??
spring.main.allow-circular-references=true
spring.jackson.serialization.write-dates-as-timestamps=false